[package]
name = "packet"
version = "0.1.0"
authors = ["SardineFish <sardine@live.cn>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
concat-idents = "1.0.0"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"