[package]
name = "proc-macros"
version = "0.1.0"
authors = ["SardineFish <sardine@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
syn = { version = "1.0.48", features = ["full"] }
quote = "1.0.7"